#!/usr/bin/env node

(function () {
    "use strict";
    
    var coveraje = require("coveraje").coveraje,
        fs = require("fs"),
        path = require("path");
    var rel = path.relative(process.cwd(), __dirname);
    
    function runTests(file) {
        return function (context) {
            return coveraje.runHelper("mocha", {
                require: "should",
                timeout: 200,
                ui: "bdd",
                globals: ["okGlobalA", "okGlobalB"],
                
                _mocha: context.mocha
            }).run(path.join(rel, file));
        };
    }
    
    var tests = {
        "hook.async": runTests("hook.async.js"),
        "hook.sync": runTests("hook.sync.js"),
        "hook.sync.nested": runTests("hook.sync.nested.js"),
        //"http.meta.2": runTests("http.meta.2.js"),
        //"http.meta": runTests("http.meta.js"),
        "runnable": runTests("runnable.js"),
        "runner": runTests("runner.js"),
        "suite": runTests("suite.js")
    };
    
    coveraje.cover(
        "var mocha = require('..');",
        tests,
        {
            useServer: true,
            globals: "node",
            resolveRequires: ["*"]
        }
    );
}());