#!/usr/bin/env node

(function () {
    "use strict";
    
    var coveraje = require("coveraje").coveraje,
        fs = require("fs"),
        path = require("path");
    var rel = path.relative(process.cwd(), __dirname);
    
    function runTests(file, helper) {
        return function (context) {
            return coveraje.runHelper(helper).run(file);
        };
    }
    
    var tests = {
        "testparser.js": runTests(path.join(rel, "testparser.js")),
        "unit": runTests(path.join(rel, "unit/scripts.js"), "nodeunit")
    };
    
    coveraje.cover(
        "var uglifyjs = require('..');",
        tests,
        {
            useServer: true,
            globals: "node",
            resolveRequires: ["*"]
        }
    );
}());