#!/usr/bin/env node

(function () {
    "use strict";
    
    var coveraje = require("coveraje").coveraje,
        fs = require("fs"),
        path = require("path"),
        filePath = path.resolve("../lib/parse-js.js");
        
    function runTests(file, helper) {
        return function (context) {
            // hack: set cache value
            require.cache[filePath] = {
                id: filePath,
                exports: context,
                loaded: true
            };
            
            return coveraje.runHelper(helper).run(file);
        };
    }
    
    var tests = {
        "testparser.js": runTests("./testparser.js"),
        "unit": runTests("./unit/scripts.js", "nodeunit")
    };
    
    coveraje.cover(
        function () {
            // always read the content from disk, so changes can be refreshed in the browser
            try {
                return fs.readFileSync(filePath, 'utf-8');
            } catch (ex) {
                return "{ /*" + ex.message + "*/ }";
            }
        },
        tests,
        {
            useServer: true,
            globals: "node"
        }
    );
}());