#!/usr/bin/env node

(function () {
    "use strict";
    
    var coveraje = require("coveraje").coveraje,
        fs = require("fs"),
        path = require("path"),
        filePath = path.resolve("../lib/parse-js.js");
        
    fs.readFile(filePath, 'utf-8', function (err, data) {
        function runTests(file, helper) {
            return function (context) {
                // hack: set cache value
                require.cache[filePath] = {
                    id: filePath,
                    exports: context,
                    loaded: true
                };
                
                return coveraje.runHelper(helper).run(file);
            };
        }
        
        if (err) throw err;
        
        var tests = {
            "testparser.js": runTests("./testparser.js"),
            "unit": runTests("./unit/scripts.js", "nodeunit")
        };
        
        coveraje.cover(data, tests, {
            useServer: true,
            globals: "node"
        });
    });
    
    return this;
}());